### ISSUE TITLE
Remove support for debugging R functions?

### ISSUE THREAD

**Issue by jalvesaq** [jalvesaq/tmp-R-Nvim#8]
This is a feature that I don't use, and it certainly would be better to have a `nvim-dap-r`. These are reasons to remove the current support for debugging functions. But I don't know if anyone is going to develop the `nvim-dap-r` and this is a reason to convert the current VimScript code to Lua.

@she3o ? @PMassicotte ? What do you think?

**Comment by PMassicotte** [comment]
I do not use it either. I simply use `browser()` at the moment. So for me, I think we can remove it.

**Comment by she3o** [comment]
I am onboard.

I don't use it, but I initially felt we shouldn't remove it before we actually have an r-debug-adapter. But since we're porting to lua, it's a good opportunity to drop some weight. It would be less convenient to drop it later after users have expected it.

**Comment by jalvesaq** [comment]
I'll remove it tomorrow. It's a bit more complicated than `grep -R -i rrst`.

**Comment by jrwishart** [comment]
Hi, I've been a long time `nvim-r` user and noticed the move to `R.nvim` this weekend and looked at migrating over. I heavily used the debugging. i.e. getting debug and browser calls to show the source code line highlighting in the appropriate buffer during debugging.

From what I can gather above, this has been dropped and line highlighting of source lines isn't supported anymore. Is this the case? If so, is there any way to re-enable it? I might be able to help since I value it highly but I'm not familiar with the implementation.

**Comment by jalvesaq** [comment]
@jrwishart, none of current `R.nvim` developers has enough interest in this feature to develop and maintain it. Hence, your options are:

- Develop the `nvim-dap-r` plugin.
- Bring back the code that I deleted, converting the VimScript code to Lua (`lua/r/debug.lua`).

**Comment by jrwishart** [comment]
I've looked into this. The development of `nvim-dap-r` is beyond me and it appears others have tried but given up due to limitations of the R language.

I have a working prototype debugging working and converted the vimscript to lua. I can look at making a PR this weekend. It is my first conversion of vimscript to lua so it might not be the most elegant since I had essentially no knowledge of vimscript before doing this.

One issue I have faced that I slowed down progress on this with an early distraction was R.nvim doesnt seem to support radian as well as nvim-r. For example if I try and use some commands I will get the message "R is not ready". Is there a way to turn on more noisy logging to figure what is causing headaches with R.nvim and radian?

**Comment by jalvesaq** [comment]
You can make nvimcom verbose in your `~/.Rprofile`:

```r
options(nvimcom.verbose = 5)
```
You can also see the communication between Neovim and R if you change line 4 of `nvimcom/src/apps/logging.h` from `#define Debug_NRS_` to `#define Debug_NRS` and, then, do in a terminal emulator:

```
tail -f /dev/shm/rnvimserver_log
```

I guess that indeed there are relevant limitations in the R language, but possibly they can be overcome by code written in C which can even replace some of R's internal functions. This is what `nvimcom` and [colorout](https://github.com/jalvesaq/colorout) do. However, packages that do that are not allowed to be on CRAN.

**Comment by PMassicotte** [comment]
Just shimmying in to say that I started to implement something also with DAP. Far from having something ready, but I am now able to communicate with `nvim-dap`.

**Comment by jrwishart** [comment]
Hi @jalvesaq , I tried the change from `#define Debug_NRS_` to `#define Debug_NRS` but it returns
```
"Server" exited with status 139
```
when I attempt to reinstall `nvimcom`

**Comment by jalvesaq** [comment]
Please, see https://github.com/R-nvim/R.nvim/wiki/Debugging-C-code-with-Valgrind

**Comment by jrwishart** [comment]
Thanks for the detailed follow up. I updated all the references to `/dev/shm/` to use `/var/log` and made it point to user owned readable files instead of system. The issue still persists. I don't believe I can go down the `valgrind` route since I am using arm (apple silicon) on `macos` and I don't believe `valgrind` can be built on this platform.

**Comment by zkamvar** [comment]
I am excited to see what @PMassicotte comes up with. I have no idea what a DAP is, but if it can restore the debugging features, this would really make my life a whole lot better. 

The value of the debugger for me wasn't the shortcut, but rather it was the ability to display the lines that were being debugged in the source code... which is extremely useful if I'm trying to debug someone else's code.
